use Restaurant
db.restaurants.find();
db.restaurants.find({}, {name:1, borough:1, cuisine:1}).pretty();
db.restaurants.find({}, {_id:0, name:1, borough:1, cuisine:1}).pretty();
db.restaurants.find({}, {name:1, borough:1, address: {zipcode:1}}).pretty();
db.restaurants.find({}, {name:1, borough: "Bronx"}).pretty();
db.restaurants.find({}, {name:1, borough: "Bronx"}).limit(5).pretty();
db.restaurants.find({}, {name:1, borough: "Bronx"}).skip(5).limit(5).pretty();
db.restaurants.find({"grades.score":{ $gt: 90 }}).pretty();
db.restaurants.find({"grades.score":{ $gt: 80, $lt: 100 }}).pretty(); db.restaurants.find({$and: [ {"grades.score":{ $gt: 80}}, {"grades.score":{$lt: 100 }}]}).pretty();
db.restaurants.find({"address.coord":{$lt:[-95.754168,0]}}).pretty();
db.restaurants.find({$and: [{"cuisine": {$ne:"American "}},{"address.coord":{$lt:[-65.754168,0]}},{"grades.score":{ $gt: 70}}]}).pretty();
db.restaurants.find({"cuisine": {$ne:"American "},"address.coord":{$lt:[-65.754168,0]},"grades.score":{ $gt: 70}}).pretty();
db.restaurants.find({"cuisine": {$ne:"American "},"borough": {$ne:"Brooklyn"}, "grades.grade":"A"}).sort({"cuisine":-1}).pretty();
db.restaurants.find({name:{ $regex: /^Wil/ }} ,{restaurant_id:1, name: 1, borough:1, cuisine:1, _id:0}).pretty();
db.restaurants.find({name:{ $regex: /ces$/ }} ,{restaurant_id:1, name: 1, borough:1, cuisine:1, _id:0}).pretty();
db.restaurants.find({name:{ $regex: /Reg/ }} ,{restaurant_id:1, name: 1, borough:1, cuisine:1, _id:0}).pretty();
db.restaurants.find({$or: [{"cuisine": "American "},{"cuisine": "Chinese"}]},{name:1, borough: "Bronx", cuisine:1 }).pretty();
db.restaurants.find({$or: [{"borough": "Staten Island"},{"borough": "Queens"},{"borough": "Bronx"},{"borough": "Brooklyn"}]},{restaurant_id:1, name:1, borough: 1, cuisine:1, _id:0 }).pretty();
db.restaurants.find({$and: [{"borough": {$ne:"Staten Island"}},{"borough": {$ne:"Queens"}},{"borough": {$ne:"Bronx"}},{"borough": {$ne:"Brooklyn"}}]},{restaurant_id:1, name:1, borough: 1, cuisine:1, _id:0 }).pretty();
db.restaurants.find({"grades.score":{$lte: 10}},{restaurant_id:1, name:1, borough: 1, cuisine:1, _id:0 }).pretty();
db.restaurants.find({$or:[{$and: [{"cuisine": {$ne:"American "}},{"cuisine": {$ne:"Chiness"}},{"name":{$regex: /Fish/}}]},{"name":{$regex: /^Wil/}}]},{restaurant_id:1, name:1, borough: 1, cuisine:1, _id:0 }).pretty();
db.restaurants.find({"grades.score":11, "grades.grade":"A", "grades.date":ISODate ("2014-08-11T00:00:00Z")},{restaurant_id:1, name:1, grades:1}).pretty();
db.restaurants.find({"grades.1.score":9, "grades.1.grade":"A", "grades.1.date":ISODate ("2014-08-11T00:00:00Z")},{restaurant_id:1, name:1, grades:1 , _id:0}).pretty();
db.restaurants.find({"address.coord.1":{ $gt: 42, $lte: 52 }},{restaurant_id:1, name:1, address:1, _id:0}).pretty();
db.restaurants.find().sort({"name": 1}).pretty();
db.restaurants.find().sort({"name": -1}).pretty();
db.restaurants.find().sort({"cuisine": 1}, {"borough": -1}).pretty();
db.restaurants.find({"address.street":null});
db.restaurants.find({"address.coord":{ $type: [1, 1] }}).pretty();
db.restaurants.find({"grades.score":{$mod:[7,0]}},{restaurant_id:1, name:1, grades:{grade:1}, _id:0}).pretty();
db.restaurants.find({name:{ $regex: /mon/ }} ,{name: 1, borough:1, address:{coord:1}, cuisine:1, _id:0}).pretty();
db.restaurants.find({name:{ $regex: /^Mad/ }} ,{name: 1, borough:1, address:{coord:1}, cuisine:1, _id:0}).pretty();